general {
    lock_cmd = pidof hyprlock || hyprlock       # dbus/sysd lock command (used by loginctl)
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on display after wake
}

# 1. Dim screen (5 mins)
listener {
    timeout = 300                                
    on-timeout = brightnessctl set 10%          # set monitor backlight to 10%
    on-resume = brightnessctl set 100%          # restore monitor backlight
}

# 2. Lock screen (10 mins)
listener {
    timeout = 600                              
    on-timeout = loginctl lock-session          # lock screen
}

# 3. Turn off monitor (15 mins)
listener {
    timeout = 900                               
    on-timeout = hyprctl dispatch dpms off      # turn off monitor
    on-resume = hyprctl dispatch dpms on        # turn on monitor
}

# 4. Suspend (120 mins)
listener {
    timeout = 7200
    on-timeout = systemctl suspend              # suspend pc
}
