# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

### ---- SOURCING MULTIPLE CONFIG FILES ---- ###

# -- MONITORS -- 
# See https://wiki.hypr.land/Configuring/Monitors/
source = ~/.config/hypr/modules/monitors.conf

# -- PROGRAMS --
source = ~/.config/hypr/modules/programs.conf

# -- KEYBINDS --
source = ~/.config/hypr/modules/keybinds.conf

# -- WINDOWRULES --
source = ~/.config/hypr/modules/windowrules.conf

# -- LOOK AND FEEL --
source = ~/.config/hypr/modules/decorations.conf

# -- ANIMATIONS --
source = ~/.config/hypr/modules/animations.conf

# -- START UP APPS --
source  = ~/.config/hypr/modules/startups.conf

# -- ENVIRONMENT VARIABLES --
source = ~/.config/hypr/modules/env.conf

# -- LAYOUT --
source = ~/.config/hypr/modules/layout.conf

# -- MISC --
source = ~/.config/hypr/modules/misc.conf

# -- INPUT --
source = ~/.config/hypr/modules/input.conf

# -- PERMISSIONS --
source = ~/.config/hypr/modules/permissions.conf


