# ---- LOOK AND FEEL (DECORATIONS) ----

# Refer to https://wiki.hypr.land/Configuring/Variables/

# https://wiki.hypr.land/Configuring/Variables/#general

source = ~/.config/hypr/modules/colors.conf

general {
    gaps_in = 7
    gaps_out = 15

    border_size = 1

    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = $active_border #rgba(b8bb26aa) #rgba(33ccffee) #rgba(00ff99ee) 45deg #GRADIENT COMMENTED OUT
    col.inactive_border = $inactive_border #rgba(595959aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = true

    layout = dwindle
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 10
    rounding_power = 10

    # Change transparency of focused and unfocused windows
    active_opacity = 0.9
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 10
        render_power = 4
        color = rgba(0a0a0add)
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 7
        passes = 3
	ignore_opacity = true

	noise = 0.02
	contrast = 1.5
        vibrancy = 0.2

	xray = false
	new_optimizations = true
    }
}




